### ISSUE TITLE
My name is Kyle and I'm a total idiot!

### ISSUE THREAD

**Issue by kyleboon** [craigburke/client-dependencies-gradle#1]
Please create a readme and make sure the code works.

**Comment by craigburke** [comment]
SHUT UP KYLE!

**Comment by jlstrater** [comment]
You might also want to add a license.

**Comment by sjurgemeyer** [comment]
WHY WAS THIS CLOSED?

**Comment by craigburke** [comment]
SHUT UP JENN!!

**Comment by jlstrater** [comment]
This is breaking my production environment. I need it NOW!

**Comment by craigburke** [comment]
SHUT YOUR GODDAMN MOUTH, SHAUN!

**Comment by kyleboon** [comment]
It has been several minutes and I don't feel my request is being taken seriously. I'd like a refund.

**Comment by craigburke** [comment]
EAT SHIT KYLE!

**Comment by craigburke** [comment]
I KNOW JENN! I BROKE IT ON PURPOSE BECAUSE I HATE YOU ALL!!!!

**Comment by kyleboon** [comment]
I wish there was code of conduct for this opensource project. I'd have you kicked out.

**Comment by jlstrater** [comment]
:+1:

**Comment by craigburke** [comment]
STUPID ASSHOLES!

:-1:
