### ISSUE TITLE
NPM dependency resolution should probably consider dist-tag

### ISSUE THREAD

**Issue by eriwen** [craigburke/client-dependencies-gradle#10]
If I fully understand the NPM conventions here, it resolves the "latest" version of a given dependency. Often module authors will tag "beta" versions with "dist-tag" that shouldn't be resolved unless that version is explicitly specified. 

See https://docs.npmjs.com/cli/dist-tag

**Comment by craigburke** [comment]
I do make an attempt to resolve whatever version expression is included (fuzzy versions, ranges, etc):
https://github.com/craigburke/client-dependencies-gradle/blob/master/src/main/groovy/com/craigburke/gradle/client/dependency/VersionResolver.groovy

You're right. Looking at the docs, I'm not handling tags correctly at the moment:
https://github.com/npm/node-semver#prerelease-tags
