### ISSUE TITLE
npe in BowerRegistry

### ISSUE THREAD

**Issue by zyro23** [craigburke/client-dependencies-gradle#17]
somehow i am seeing `NullPointerException`s for bower dependencies that used to resolve with `bower-installer-gradle`. while this one works:

```
clientDependencies {
    bower {
        jquery "2.0.0"
    }
}
```

this one gives a npe:

```
clientDependencies {
    bower {
        angular "1.5.0"
    }
}
```

stacktrace:

```
Caused by: java.lang.NullPointerException: Cannot get property 'fullVersion' on null object
        at com.craigburke.gradle.client.registry.BowerRegistry.loadDependency(BowerRegistry.groovy:125)
        at com.craigburke.gradle.client.plugin.ClientDependenciesPlugin$_installDependencies_closure4$_closure10.doCall(ClientDependenciesPlugin.groovy:75)
        at groovyx.gpars.pa.CallClosure.call(CallClosure.java:47)
```

from a quick look at the repositories, i can just offer a wild guess: maybe a mismatch of the `bower.json` `version` and the actual tag name has something to do with it? they seem to be the same for `jquery` but not for a lot of other packages (`v` prefix)..

**Comment by craigburke** [comment]
Huh, Interesting. I've been using npm for almost all my dependencies with this so I haven't run into this, but I'll bet your hunch is correct.

I'm planning on pushing a new release out today and I'll try to get a fix for this in there too.

**Comment by craigburke** [comment]
@zyro23 give 0.3.0 a spin if you would.

**Comment by zyro23** [comment]
looks like tags with a `v` prefix do work now. however, i am still seeing a npe, now for `angular-material`. that one defines its `bower.json` dependencies like `"dependencies": { "angular": "^1.4.8" }`

**Comment by craigburke** [comment]
@zyro23 hmmm.... it should support "caret ranges" like that. I'll take a look and see what I messed up.

**Comment by craigburke** [comment]
@zyro23 I see the issue. `angular-material` has the following 4 dependencies:

```
    "angular": "^1.4.8",
    "angular-animate": "^1.4.8",
    "angular-aria": "^1.4.8",
    "angular-messages": "^1.4.8"
```

Those resolve fine. But those last three have an additional dependency on `angular@1.5.0` So they're colliding as they all try to resolve those at the same time. I'll fix that.

In the meantime, this works:

```
clientDependencies {
    bower {
        'angular'('1.5.0')
        'angular-material'('1.0.6', exclude: 'angular')
    }
}
```

**Comment by craigburke** [comment]
I'm going to close this ticket and add a new one. I really appreciate the bug reports. This is incredibly helpful.
