### ISSUE TITLE
Bower throws NPE when same dependency resolves in parellel

### ISSUE THREAD

**Issue by craigburke** [craigburke/client-dependencies-gradle#18]
From #17 @zyro23

NPE is thrown with the following:

```
clientDependencies {
    bower {
        'angular-material'('1.0.6')
    }
}
```

angular-material has the following 4 dependencies:

```
"angular": "^1.4.8",
"angular-animate": "^1.4.8",
"angular-aria": "^1.4.8",
"angular-messages": "^1.4.8"
```

Those resolve fine. But those last three have an additional dependency on angular@1.5.0 So they're colliding as they all try to resolve those at the same time. I'll fix that.

**Comment by craigburke** [comment]
Should be resolved now in `0.3.1` It's still much slower than I'd like. I'll be working on some performance improvements in `0.4.0` though.

**Comment by zyro23** [comment]
thanks! slower in terms of resolution or because of the download? i was suprised to see bower dependencies clone whole repos which made up ~500mb for some angular, bootstrap, etc. while npm works super fast compared to that downloading only a fraction of that (but still all relevant files ofc)..

**Comment by craigburke** [comment]
Yeah exactly. It's because of the download itself. The equivalent using npm is much faster and takes up a fraction of the space. You have to explicitly define all the dependencies because they are all listed as peer dependencies in npm.

```
clientDependencies {
    npm {
        'angular'('1.5.0')
        'angular-material'('1.0.6')
        'angular-animate'('1.5.0')
        'angular-aria'('1.5.0')
        'angular-messages'('1.5.0')
    }
}
```
