### ISSUE TITLE
clientReport task on version 0.3.1 fails

### ISSUE THREAD

**Issue by filipblondeel** [craigburke/client-dependencies-gradle#23]
Hi,

The 'clientReport' task on version 0.3.1 always fails because Groovy complains about a missing method. 

See [gradle-output.txt](https://github.com/craigburke/client-dependencies-gradle/files/179318/gradle-output.txt) for the output I get when I run `./gradlew clientReport --stacktrace`.

I also attached a test project that can be used to reproduce the issue: [client-dependencies-test-project.zip](https://github.com/craigburke/client-dependencies-gradle/files/179298/client-dependencies-test-project.zip)

**Comment by filipblondeel** [comment]
See pull request #24 for a fix for this issue.

**Comment by craigburke** [comment]
Merged.
