### ISSUE TITLE
npm - support scoped packages

### ISSUE THREAD

**Issue by zyro23** [craigburke/client-dependencies-gradle#25]
it seems that currently, scoped packages are not supported.

for example, the angular2-material alpha packages are published under the `angular2-material` scope, e.g.: `npm install --save @angular2-material/core`. see
- https://github.com/angular/material2
- https://www.npmjs.com/package/@angular2-material/core
- https://docs.npmjs.com/misc/scope

```
:clientInstall FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':clientInstall'.
> groovy.json.JsonException: groovy.json.JsonException: Unable to process url: https://registry.npmjs.org/@angular2-material/core
```

support for scoped packages would be great :)

**Comment by craigburke** [comment]
Great idea! :+1:

**Comment by zyro23** [comment]
the registry resolution seems just be be a matter of url-encoding:

```
clientDependencies {
    npm {
        "@angular2-material%2Fcore" "2.0.0-alpha.1"
```

that works - so fixing that is hopefully an easy one.

if manually encoding the slash as `%2f` like above, the default target is `assets/vendor/@angular2-material%2Fcore`... would be great if thats customizable easily but i see you are taking care of that in #26 already :D thanks man!

**Comment by craigburke** [comment]
@zyro23 Yeah, I thought it would be a lot harder but I have it fixed locally. I'm going to push it and do an `0.4.2` release with it. Really appreciate you talking through some of these issues with me.

**Comment by craigburke** [comment]
On an unrelated note are you on twitter? I'd love to harass you on there as well :smile:
