### ISSUE TITLE
Please add twitter as a dependency source

### ISSUE THREAD

**Issue by kyleboon** [craigburke/client-dependencies-gradle#30]
https://gist.github.com/rauchg/5b032c2c2166e4e36713

**Comment by craigburke** [comment]
@kyleboon please add this in your `build.gradle` to see if it help

```
clientInstall {
    doLast { 
        println 'SHUT UP KYLE!'
    }
}
```

**Comment by kyleboon** [comment]
That did not work.

**Comment by craigburke** [comment]
what version of Windows are you using? 95? 98?

**Comment by kyleboon** [comment]
ibm os/2 warp 4

**Comment by craigburke** [comment]
I just spun up a Microsoft Bob VM and it's running fine on there. You're clearly doing something wrong.

![image](https://cloud.githubusercontent.com/assets/793574/14028381/a25d1fda-f1d2-11e5-8da0-698c8f53f2d6.png)
