### ISSUE TITLE
angular2 transitive dependencies and eachFile

### ISSUE THREAD

**Issue by kensiprell** [craigburke/client-dependencies-gradle#36]
Hi Craig,

Thanks for working on this! Once you get it finished it should go in the Grails angular-profile.

I'm trying to install angular2 in a Grails 3.1.4 app using the snippet below along with version 0.5.0 of your plugin. Unfortunately, it also installs the transitive dependencies, and I need to do those individually. Am I doing something wrong, or will this work in a newer release? I see you're up to 1.0.0-SNAPSHOT.

```
clientDependencies {
    installDir = 'grails-app/assets/npm'

    npm {
        'angular2'('2.0.0-beta.14') {
            include 'src/**/*.js'
            exclude '**/*.ts'
            transitive false
            into 'javascripts/' 
        }
    }
}
```

Also, I couldn't get `into` or the `eachFile` closure to work. For example, I wanted to have the angular files in `grails-app/assets/npm/javascripts/angular2`, but they end up in  `grails-app/assets/npm/angular2/javascripts/angular2`. 

I suspect I'm misusing the closure technique, but I assumed it would accept the same properties as the simpler method.

Thanks again,

Ken

**Comment by craigburke** [comment]
@kensiprell yeah, the closure is just a Gradle copy spec. So try this:

```
'angular2'('2.0.0-beta.14', transitive: false, into: 'javascripts') {
    include 'src/**/*.js'
    exclude '**/*.ts'
}
```

**Comment by kensiprell** [comment]
Thanks, it worked! I should quit doing this late after work.
