### ISSUE TITLE
Unable to clean cached dependencies on Windows

### ISSUE THREAD

**Issue by jruuttun** [craigburke/client-dependencies-gradle#46]
When running gradle in daemon mode, some git object files are left open/locked, preventing a subsequent run of `clientClean`. An example on Windows7 + Git Bash (with `org.gradle.daemon = true` defined in .gradle/gradle.properties):

<pre>
$ gradlew clientInstall
:clientInstall

BUILD SUCCESSFUL

Total time: 4.588 secs

$ gradlew clientClean
:clientClean FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':clientClean'.
> Unable to delete file: C:\Users\me\git\projectx\build\client-cache\bower\some-js-lib\1.2.3\.git\objects\pack\pack-df66b80a9b56f748396e2aa74daad6124db34c23.pack

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.744 secs
</pre>

This can be worked around by disabling the gradle daemon with the `--no-daemon` switch. The issue remains for some IDE integrations where the daemon is always used. See e.g. https://discuss.gradle.org/t/disable-gradle-daemon-in-eclipse/11503. The tool is currently broken on these platforms.

A likely fix would be to [close()](http://ajoberstar.org/grgit/docs/groovydoc/org/ajoberstar/grgit/Grgit.html#close%28%29) the Grgit instance in GitResolver.groovy after use.

**Comment by craigburke** [comment]
@jruuttun wow. thanks for reporting this. I'll try to get a new version out that hopefully addresses this.
