### ISSUE TITLE
Improve custom registry documentation

### ISSUE THREAD

**Issue by mrampson** [craigburke/client-dependencies-gradle#48]
I defined a custom registry, cradle doesn't seem to complain about it, but the custom registry doesn't look like it is searched for dependency.  Also, it would be nice to be able to override the default registry and be able to tell the plugin to just use a particular registry in the case of you using an npm proxy cache.  Or am I missing something.

**Comment by mrampson** [comment]
update:  was able to get it to work.  I'll try to put a pull request in on how to use a custom registry so it is more clear.

**Comment by craigburke** [comment]
@mrampson thanks for the heads up. The custom registries documentation is definitely lacking. If you don't get around to a PR I'll take a look and try to expand that.

**Comment by mrampson** [comment]
Added a PR to update the docs a little.

**Comment by craigburke** [comment]
@mrampson looks great! Thanks so much for the PR!!!
