### ISSUE TITLE
Any interest in making this useful to devs who might use npm and gradle?

### ISSUE THREAD

**Issue by mrampson** [craigburke/client-dependencies-gradle#50]
In other words, you might have a project that has javascript and java.  Our JS folks tend to use javascript tools (npm, etc) and java folks don't want to know anything about it.  The idea is that they could both be used and have it work together.

Some things that would need to change is where it looks for package.json and the sections of package.json that is looks at (devDependencies for instance).

Might need to put things in node_modules or have the ability to copy certain sub directories in the package to certain places in the file system (or both).

**Comment by craigburke** [comment]
@mrampson I'm trying to avoid using node directly with this plugin (just want to use npm to resolve dependencies). I'm wondering if this gradle plugin might better suite your need (I've used it and it works really well): https://github.com/srs/gradle-node-plugin
