### ISSUE TITLE
Example on DefinitelyTyped

### ISSUE THREAD

**Issue by animator013** [craigburke/client-dependencies-gradle#54]
Hi there.

Can you make an example how to download typings with this plugin ? Or should I just stick with this and another plugin of yours https://github.com/craigburke/bower-installer-gradle ?

Seems to be also related to #53.

Thank your for your time.

**Comment by craigburke** [comment]
@animator013 I just resolved #53 and released version `1.2.0` see if that works a little better for you.

**Comment by craigburke** [comment]
I'm closing this. Feel free to add another issue if you're still running into issues with this.
