### ISSUE TITLE
Add support for yarn registry

### ISSUE THREAD

**Issue by rahulsom** [craigburke/client-dependencies-gradle#57]
NPM is so yesterday.

**Comment by craigburke** [comment]
@rahulsom I'm looking at it for ideas to steal. I'd love to do something like `yarn.lock`:
https://yarnpkg.com/en/docs/yarn-lock

**Comment by craigburke** [comment]
Yarn uses its own registry I'd like to add support for that `https://registry.yarnpkg.com`
