### ISSUE TITLE
Common Image formats used in CSS accompanying js packages not downloaded 

### ISSUE THREAD

**Issue by fsparv** [craigburke/client-dependencies-gradle#66]
It seems that https://github.com/craigburke/client-dependencies-gradle/blob/master/src/main/groovy/com/craigburke/gradle/client/plugin/ClientDependenciesExtension.groovy#L50 doesn't
include most types of images by default. This caused me significant confusion and delay because I assumed that since I was seeing SVG files pulled down in one package, image files must be included by default, and therefore I assumed there was a problem with the package on NPM... (the root issue was a 404 for an image referenced by a CSS file that did get included).

It would be nice if the documentation would either list the defaults (I did actually read it, but had no reason to believe you would be excluding some image types and not others), or if the defaults could be more liberal and include png, jpg  and gif etc... (or both!)

**Comment by craigburke** [comment]
@fsparv good point, these should probably be added by default. I'll also clarify the docs.
