### ISSUE TITLE
Unable to reach npm registry behind proxy due to User-Agent property

### ISSUE THREAD

**Issue by jeffmwells** [craigburke/client-dependencies-gradle#67]
I am behind a corporate proxy trying to use this plugin. When I use a custom registry setting to reach http://registry.npmjs.org/some-dependency I receive a 407 error. 

I tried using the actual URL.getText() call from the build file and it succeeds when I don't pass the user agent, but reproduces the 407 error when I pass the User-Agent property as the default value.

**Comment by craigburke** [comment]
Ok. I'll add this to the 1.4.0 release. I'm thinking adding a `userAgent` property that could be set to null if you want the user agent not to be set would make sense.

**Comment by jeffmwells** [comment]
Sounds like a great solution to me. Thanks for the very quick response!

**Comment by comradum** [comment]
Hello,

when it will be fixed?
