### ISSUE TITLE
Ambiguous method overloading for method groovy.json.JsonSlurper#parse

### ISSUE THREAD

**Issue by hamdrew** [craigburke/client-dependencies-gradle#69]
* client-dependencies-gradle version 1.3.1
* Gradle version 2.5
* Java 8
* Mac OS X 10.12.2

I get the following error when I attempt to run `clientInstall`, `clientRefresh`, or `clientReport`:

```text
> Ambiguous method overloading for method groovy.json.JsonSlurper#parse.
  Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
  	[class [B]
  	[class [C]
  	[class java.io.File]
  	[class java.io.InputStream]
  	[class java.io.Reader]
  	[class java.net.URL]
```

Attached are the debug log with stacktrace (`./gradlew clientReport --debug --stacktrace`)  and my gradle build file. Let me know if I can provide any more information!

[stacktrace.zip](https://github.com/craigburke/client-dependencies-gradle/files/679260/stacktrace.zip)

**Comment by Ejgood21** [comment]
I'm getting the same thing with:
-client-dependencies-gradle version 1.3.1
-Gradle version 3.3
-Java 8
-Windows 8
