### ISSUE TITLE
How to download a specific file?

### ISSUE THREAD

**Issue by TomDmitriev** [craigburke/client-dependencies-gradle#70]
I encountered this problem when I tried to migrate from [bower-installer-gradle](https://github.com/craigburke/bower-installer-gradle) plugin to this one. The following works in the former

    bower {
        ...
        requirejs('http://requirejs.org/docs/release/2.3.2/minified/require.js') {
            source 'index.js' >> 'require.min.js'
        }
        ...

However this plugin throws an error
> org.eclipse.jgit.errors.NoRemoteRepositoryException: http://requirejs.org/docs/release/2.3.2/minified/require.js: http://requirejs.org/docs/release/2.3.2/minified/require.js/info/refs?service=git-upload-pack not found

**Comment by erichelgeson** [comment]
I'm not sure how the old plugin worked, but to just grab require.min.js from that repo, you could try something like:

```groovy
clientDependencies {
    bower {
        'requirejs'('2.3.2') {
            include 'require.min.js'
        }
    }
}
```

**Comment by TomDmitriev** [comment]
I could try this if require.min.js was available via bower, which is not the case, https://github.com/requirejs/requirejs/issues/737.

**Comment by craigburke** [comment]
@TomDmitriev you should be able to grab this directly from npm:
```
clientDependencies {
    npm {
     requirejs('2.3.2') {
        include 'require.min.js'
    }
}
```

**Comment by craigburke** [comment]
I'm closing this. Feel free to comment if that doesn't work and I'll reopen.
