### ISSUE TITLE
License needed

### ISSUE THREAD

**Issue by eriwen** [craigburke/client-dependencies-gradle#8]
Similar to https://github.com/craigburke/karma-gradle/issues/7, I need your written permission to use this plugin, and this is best achieved through a publicly stated LICENSE file.

Jeff Atwood has [some interesting thoughts](http://blog.codinghorror.com/pick-a-license-any-license/) on this that may be worth a read. 

I'm very interested in this so I hope you'll consider it.

**Comment by craigburke** [comment]
@eriwen thanks for the reminder. I'll add that to both projects today.

**Comment by eriwen** [comment]
:rainbow: :star2: :+1:
