### ISSUE TITLE
import dependencies from bower.json or package.json

### ISSUE THREAD

**Issue by xetra11** [craigburke/client-dependencies-gradle#81]
Hey there!
I'm in need of your bower plugin functionality and I wonder if there is a way to import the dependencies declared in a *bower.json* anyhow? My project is a co-project with some frontend guys who don't use gradle and I don't want to synced the *bower.json* with my gradle.build file.

Any solution for that?

Thanks!

**Comment by craigburke** [comment]
The gradle node plugin might be a better fit if you frontend folks don't want to touch gradle: 
https://github.com/srs/gradle-node-plugin
