### ISSUE TITLE
Feature Request: Provide a configuration to include all files for a package

### ISSUE THREAD

**Issue by amimas** [craigburke/client-dependencies-gradle#93]
Hello,

I'd like to use this plugin for downloading various packages that needs to be included in my project. I like the idea of not having to "install" npm/bower in order to achieve this. Based on what I've read so far in this project's guide, it seems this plugin has a default setting for including files for only certain extentions.

While that may be desired in some cases, it probably doesn't help everyone. I know you have an option to include additional file extentions, but that's extra work for users to manage. For example: I want to simply get everything for a bower package. But I have to go through the entire package myself to know if certain file extensions need to be manually added to `client-dependencies-gradle` configuration. If I choose to upgrade the version of certain package, I have to go through this exercise all over again to make sure I'm getting everything.

Instead of having some default file extensions, can it be set to get everything by default? I think that will be most desirable option and let users use `copyExcludes` configuration to opt-out of whatever files they do not want to receive.

Or, another option could be to have a separate configuration (i.e. `includeAllFiles`). This configuration will override/take precedence over `fileExtensions` configurations.

**Comment by craigburke** [comment]
You should be able to do that by overriding the default copy setting
```
clientDependencies {
    defaultCopy = { include '**' }
}
```

**Comment by amimas** [comment]
Great!! I'll try that out.
